! New version of the bimodulus setter. Did not want to modify setBimod since it is used in other macros; too much work to code around the original.

! Et, Ec, nut, nuc, method (1- first invariant Liu, 2 - first invariant tanh, 3 - Latorre and Montans (unfinished)), beta (first invariant tanh)
tb,user,1,1,5
tbtemp,0
tbdata,1,ARG1,ARG2,ARG3,ARG4,ARG5-1,ARG6
tb,state,1,,6
outres,svar,all ! turn state variables on for solution