! rv

*if,earniugwrqhbdsabutgdvtwqvuxhbsahibfoeudbahisxbnhjayuwbqdbajhnxiansijdfjiasnidnijxi,eq,0,then
	*set,earniugwrqhbdsabutgdvtwqvuxhbsahibfoeudbahisxbnhjayuwbqdbajhnxiansijdfjiasnidnijxi,1

	/RGB,INDEX,100,100,100, 0   
	/RGB,INDEX, 80, 80, 80,13   
	/RGB,INDEX, 60, 60, 60,14   
	/RGB,INDEX, 0, 0, 0,15  
	/REPLOT 
*else
	*set,earniugwrqhbdsabutgdvtwqvuxhbsahibfoeudbahisxbnhjayuwbqdbajhnxiansijdfjiasnidnijxi,0
	/RGB,INDEX, 0, 0, 0, 0  
	/RGB,INDEX, 60, 60, 60,13   
	/RGB,INDEX, 80, 80, 80,14   
	/RGB,INDEX,100,100,100,15   
	/REPLOT 
*endif